### PR TITLE
Add developer documentation for 0.2

### PR DESCRIPTION
**Pull request by miina**
Adds general documentation about caching, precaching, offline templates, offline commenting; also lists out all actions and filters added by the feature plugin.

### CODE REVIEW

**Comment by miina** [comment]
@westonruter I added a brief description about the features added meanwhile since the last update to Readme file and also listed out all actions and filters.

Let me know if there seems to be anything missing or if you think it would be good add some additional examples.

**Comment by westonruter** [comment]
> However, (not right now but in the future) what do you think of keeping `readme.md` and `readme.txt` as separate files where `readme.md` would contain developer focused information and where `readme.txt` would also include screenshots for the plugins page in WP repo and more relevant information for the plugin users who won't necessarily be developers only? It feels like these two files have slightly different purposes.

The thing is that if there is a `readme.md` then GitHub will use it to display rather than the `readme.txt`, whereas WordPress.org only recognizes the latter. So by having it all in `readme.txt` then Markdown generator in dev-lib will automatically keep them in sync, with GitHub getting a nicely-formatted readme (in Markdown) and WordPress.org getting its required readme format as well.

**Comment by miina** [comment]
> The thing is that if there is a readme.md then GitHub will use it to display rather than the readme.txt, whereas WordPress.org only recognizes the latter. So by having it all in readme.txt then Markdown generator in dev-lib will automatically keep them in sync, with GitHub getting a nicely-formatted readme (in Markdown) and WordPress.org getting its required readme format as well.


What I was thinking was that maybe `readme.md` could be more developer-focused (since it's displayed in Github) and `readme.txt` would be more WP.org-focused with the screenshots etc. and not necessarily only developer-focused but also considering non-technical plugin users. That perhaps they shouldn't be exact match and automatically synced?

**Comment by westonruter** [comment]
@miina I tried running `npm run generate-readme` and it seems that all of the Offline Commenting 
section isn't moved over to `readme.txt` yet. I did so in 9fb310b. Let me know if I missed anything.

> What I was thinking was that maybe `readme.md` could be more developer-focused (since it's displayed in Github) and `readme.txt` would be more WP.org-focused with the screenshots etc. and not necessarily only developer-focused but also considering non-technical plugin users. That perhaps they shouldn't be exact match and automatically synced?

I think since this is a feature plugin that is intended for developers that it is fine and even preferred to have the developer information displayed on WordPress.org.

**Comment by miina** [comment]
> I think since this is a feature plugin that is intended for developers that it is fine and even preferred to have the developer information displayed on WordPress.org.

Okay, makes sense!

Thanks for moving the Offline Commenting section over, too.

**Pull request merged**
