### PR TITLE
Ensure $current_screen global is set before applying admin_title filter

### LINKED ISSUE #206: admin_title filter called without ensuring current_screen is set
In /wp-admin/error.php, the `admin_title` filter is used without ensuring that the current_screen is set: https://github.com/xwp/pwa-wp/blob/7cf111f43dff028d6331009eabdc25848e6cd44f/wp-admin/error.php#L45

admin-header.php does this with https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-header.php#L29:L32

before using the filter in https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-header.php#L68.

This is causing the fatal error reported in https://github.com/woocommerce/woocommerce-admin/issues/2732 .

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #206.

### CODE REVIEW

**Comment by nuvoPoint** [comment]
We have implemented this fix and are keeping an eye on the log files for the next couple of hours to see if this fixes #206

**Comment by nuvoPoint** [comment]
We haven't see the fatal error yet in our logs, but now we are getting the following:

`PHP Notice: Undefined index: hook_suffix in /var/www/html/wp-admin/includes/class-wp-screen.php on line 213`

The only two things changed in our setup is this fix and #179

**Comment by westonruter** [comment]
@nuvoPoint Thanks for that. I've also set `$hook_suffix` to address this in ad7adab.

**Comment by nuvoPoint** [comment]
It seems to work fine now with $hook_suffix - thanks!

**Pull request merged**
