### PR TITLE
Fix property case in Navigation_Routing_Component

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### CODE REVIEW

**Comment by westonruter** [comment]
@szepeviktor Now that we've moved the repo over to the GoogleChromeLabs org, could you please [sign the CLA](https://cla.developers.google.com/about/google-individual), if you haven't done so already? Then please rebase the branch or merge the latest from `master` to trigger a new build.

**Comment by szepeviktor** [comment]
@westonruter Could you please help be: cla signed, 2×changing base and CI still points to old repo

**Comment by szepeviktor** [comment]
in #241

**Comment by westonruter** [comment]
@szepeviktor ok, sorry, I meant a `git-rebase`. You can just merge the latest changes from GoogleChromeLabs:master instead.

**Comment by westonruter** [comment]
@szepeviktor I'm curious. How was this identified as an error? The `WP_Theme::__get()` method has:

```
			case 'version':
				return $this->get( 'Version' );
// ...
			default:
				return $this->offsetGet( $offset );
```

But then `WP_Theme::offsetGet()` has:

```
			case 'Version':
			case 'Status':
				return $this->get( $offset );
```

But I'm not clear on how this issue was detected in the first place. How is this detected with static analysis?

The benefit of this change is that the fallback call to `WP_Theme::offsetGet()` is avoided.

**Review by westonruter — APPROVED** [review]

**Comment by szepeviktor** [comment]
the phpstan wordpress extension known about 

https://github.com/szepeviktor/phpstan-wordpress/blob/master/src/WpThemeMagicPropertiesClassReflectionExtension.php#L16-L19

these magic properties

https://github.com/WordPress/WordPress/blob/cad04902d6a162ba8320f82a6c65c7eb58cf9759/wp-includes/class-wp-theme.php#L457-L472

**Comment by szepeviktor** [comment]
...also magic __get() knows it as `version`

https://github.com/WordPress/WordPress/blob/cad04902d6a162ba8320f82a6c65c7eb58cf9759/wp-includes/class-wp-theme.php#L490

**Pull request merged**
