### PR TITLE
Proper PHPStan configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
`composer require --dev szepeviktor/phpstan-wordpress --ignore-platform-reqs` and you are ready!

### CODE REVIEW

**Comment by szepeviktor** [comment]
I see your project is bound to PHP 5.6, so I leave all these up to you!!

**Comment by westonruter** [comment]
Thanks for the PR. It seems this would require a dirty `composer.json` then given the PHP 5.6 requirement? If so, it doesn't seems ideal.

**Comment by westonruter** [comment]
I've taken some of the config improvements and put them in another PR: #563.

**Comment by szepeviktor** [comment]
> Thanks for the PR. It seems this would require a dirty `composer.json` then given the PHP 5.6 requirement? If so, it doesn't seems ideal.

"Ideal" and PHP 5.6 in one sentence? :)

**Pull request closed without merging**
